### ISSUE TITLE
Issues with sending transactions (High delay)

### ISSUE THREAD

**Issue by wbelhomsi** [blockworks-foundation/lite-rpc#347]
Hi there,

I'm adding lite-rpc to enhance my chances of getting my transactions included. I have a server on the cloud with some security groups shielding it.
As a test, I'm trying only to use the `lite-rpc` to send the transaction to test its speed. In some cases, I've been getting around 21-26 seconds difference between when I send the transaction and when it gets included.

Im using Solana's web3js `Connection`:
```
const sendingBoost = new Connection('http://127.0.0.1:8890', 'confirmed');
```

I have simply cloned the repo, ran `cargo run --release` and then ran the following:

```
RUST_BACKTRACE=1 RUST_LOG=info LITE_RPC_HTTP_ADDR=0.0.0.0:8890 LITE_RPC_WS_ADDR=0.0.0.0:8891 RPC_ADDR=https://RPC_URL/API_KEY WS_ADDR=wss://RPC_URL/API_KEY ./lite-rpc
```

```
2024-03-01T13:26:21.382174Z  INFO solana_lite_rpc_core::stores::block_information_store: Cleaned 142 block info    
2024-03-01T13:26:21.407404Z  INFO solana_lite_rpc_core::stores::tx_store: Cleaned 147140 transactions    
2024-03-01T13:27:21.408198Z  INFO solana_lite_rpc_core::stores::block_information_store: Cleaned 142 block info    
2024-03-01T13:27:21.431499Z  INFO solana_lite_rpc_core::stores::tx_store: Cleaned 147046 transactions    
2024-03-01T13:27:21.864677Z  WARN solana_lite_rpc_services::quic_connection: Could not establish connection with 3SkE34PVeGck2ArEffFKjihrQgURsvnoTAhitsNXNzXd    
2024-03-01T13:28:21.432156Z  INFO solana_lite_rpc_core::stores::block_information_store: Cleaned 148 block info    
2024-03-01T13:28:21.457325Z  INFO solana_lite_rpc_core::stores::tx_store: Cleaned 157057 transactions    
2024-03-01T13:29:21.458204Z  INFO solana_lite_rpc_core::stores::block_information_store: Cleaned 140 block info    
2024-03-01T13:29:21.482479Z  INFO solana_lite_rpc_core::stores::tx_store: Cleaned 149376 transactions    
2024-03-01T13:30:21.483011Z  INFO solana_lite_rpc_core::stores::block_information_store: Cleaned 142 block info    
2024-03-01T13:30:21.506700Z  INFO solana_lite_rpc_core::stores::tx_store: Cleaned 139413 transactions    
2024-03-01T13:30:30.758412Z  WARN solana_lite_rpc_services::quic_connection: Could not establish connection with DRpbCBMxVnDK7maPM5tGv6MvB3v1sRMC86PZ8okm21hy    
2024-03-01T13:30:42.765680Z  WARN solana_lite_rpc_services::quic_connection: Could not establish connection with Fd7btgySsrjuo25CJCj7oE7VPMyezDhnx7pZkj2v69Nk
```

Im wondering if there are any ports that I shouldn't be blocking (especially UDP ports), couldn't find any list of recommended ports to be whitelisted
Also the `Could not establish connection` is weird, is there a reason I'm hitting that?
Native transfers are also sometimes failing:
```
ERR SendTransactionError: failed to send transaction: Internal error
    at Connection.sendEncodedTransaction (XXX/node_modules/@solana/web3.js/src/connection.ts:5921:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Connection.sendRawTransaction (XXX/node_modules/@solana/web3.js/src/connection.ts:5880:20)
```

Any help would be appreciated. Thanks

Server I'm trying on has: 64 GB Ram and 32 CPU

**Comment by algotradingstrategies** [comment]
Wondering the same.

Using public RPCs like quicknode etc, I was seeing so many of "tx exceeding block height" and also high delays (measured in slots) between sending the tx and getting included, so I was very excited trying liteRPC. However, also with liteRPC seeing the same - many "exceeding block height" and long delays. Actually, quicknode seems even slightly better. Shouldn't running my own local (lite) RPC yield an improvement? 

Wondering if anything could be wrong in my setup too?

Here is my ....:9091/metrics output:

```
# HELP literpc_connections_to_keep Number of connections to keep asked by tpu service
# TYPE literpc_connections_to_keep gauge
literpc_connections_to_keep 6
# HELP literpc_current_slot Current slot seen by last rpc
# TYPE literpc_current_slot gauge
literpc_current_slot 251828514
# HELP literpc_estimated_slot Estimated slot seen by last rpc
# TYPE literpc_estimated_slot gauge
literpc_estimated_slot 251828514
# HELP literpc_messages_in_replay_queue Number of transactions waiting for replay
# TYPE literpc_messages_in_replay_queue gauge
literpc_messages_in_replay_queue 0
# HELP literpc_nb_active_connections Number quic tasks that are running
# TYPE literpc_nb_active_connections gauge
literpc_nb_active_connections 6
# HELP literpc_nb_active_quic_connections Number of quic connections open
# TYPE literpc_nb_active_quic_connections gauge
literpc_nb_active_quic_connections -7119
# HELP literpc_nb_cluster_nodes Number of cluster nodes in saved
# TYPE literpc_nb_cluster_nodes gauge
literpc_nb_cluster_nodes 3386
# HELP literpc_quic_connection_timedout Number of times connection timedout
# TYPE literpc_quic_connection_timedout gauge
literpc_quic_connection_timedout 97
# HELP literpc_quic_finish_errored Number of times finish errored
# TYPE literpc_quic_finish_errored gauge
literpc_quic_finish_errored 4
# HELP literpc_quic_finish_timedout Number of times finish timedout
# TYPE literpc_quic_finish_timedout gauge
literpc_quic_finish_timedout 2
# HELP literpc_quic_nb_connection_requested Number of connections requested
# TYPE literpc_quic_nb_connection_requested gauge
literpc_quic_nb_connection_requested 2343
# HELP literpc_quic_nb_send_transaction_successful Number of times send transaction was successful
# TYPE literpc_quic_nb_send_transaction_successful gauge
literpc_quic_nb_send_transaction_successful 3010
# HELP literpc_quic_nb_send_transaction_tried Number of times send transaction was tried
# TYPE literpc_quic_nb_send_transaction_tried gauge
literpc_quic_nb_send_transaction_tried 3016
# HELP literpc_quic_tasks Number of connections to keep asked by tpu service
# TYPE literpc_quic_tasks gauge
literpc_quic_tasks 0
# HELP literpc_rpc_responding If RPC is responding
# TYPE literpc_rpc_responding gauge
literpc_rpc_responding 1
# HELP literpc_rpc_send_tx RPC call send transaction
# TYPE literpc_rpc_send_tx counter
literpc_rpc_send_tx 246
# HELP literpc_tx_batch_size batchsize of tx sent by literpc
# TYPE literpc_tx_batch_size gauge
literpc_tx_batch_size 1
# HELP literpc_txs_confirmed Number of Transactions Confirmed
# TYPE literpc_txs_confirmed counter
literpc_txs_confirmed 229
# HELP literpc_txs_finalized Number of Transactions Finalized
# TYPE literpc_txs_finalized counter
literpc_txs_finalized 228
# HELP literpc_txs_in_channel Transactions in channel
# TYPE literpc_txs_in_channel gauge
literpc_txs_in_channel 0
# HELP literpc_txs_in_store Transactions in store
# TYPE literpc_txs_in_store gauge
literpc_txs_in_store 467118
# HELP literpc_txs_send_timer Time to send transaction batch
# TYPE literpc_txs_send_timer histogram
literpc_txs_send_timer_bucket{le="0.005"} 230
literpc_txs_send_timer_bucket{le="0.01"} 230
literpc_txs_send_timer_bucket{le="0.025"} 230
literpc_txs_send_timer_bucket{le="0.05"} 230
literpc_txs_send_timer_bucket{le="0.1"} 230
literpc_txs_send_timer_bucket{le="0.25"} 230
literpc_txs_send_timer_bucket{le="0.5"} 230
literpc_txs_send_timer_bucket{le="1"} 230
literpc_txs_send_timer_bucket{le="2.5"} 230
literpc_txs_send_timer_bucket{le="5"} 230
literpc_txs_send_timer_bucket{le="10"} 230
literpc_txs_send_timer_bucket{le="+Inf"} 230
literpc_txs_send_timer_sum 0.020103787000000005
literpc_txs_send_timer_count 230
# HELP literpc_txs_sent Number of transactions forwarded to tpu
# TYPE literpc_txs_sent counter
literpc_txs_sent 230
```

Should liteRPC be just as fast for sending transactions to the network as running my own full RPC Solana node, or would the latter be still suprior in getting my transactions sent&included quickly?

**Comment by godmodegalactus** [comment]
Do you have any staked identity ?
Solana QUIC connections need a staked identity to get better priority over network. Without staked identity, Solana leader gives us unstaked connections, which is rate limited, and they are restricted to just 50 unstaked connections with very bad network parameters. This issue cannot be solved without giving changing solana validator code. When you send transactions via RPC provider usually they have a validator with high stakes, which gives them higher priority at network level.

With lite-rpc there is a parameter called TPU_FANOUT which controls how many next leaders you should send the transactions. With higher fanout you send to more leaders. Usually immediate leaders are always occupied with serving staked validators, that is why Lite-RPC is able to send transaction to a leader which is few slots later with an unstaked connections.

**Comment by wbelhomsi** [comment]
Thanks for the detailed reply. I do not have a staked identity, I'll need to check the quic proxy you provide to enhance that, but then I'll need to find a staked validator (or need to stake myself).
Happy to close that for now unless you have some more comments. I'll also play around with the fanout
