### ISSUE TITLE
Getting failed instruction when attempting bench

### ISSUE THREAD

**Issue by jnikoletich** [blockworks-foundation/lite-rpc#89]
Hi,

When I attempt to run cargo test, I receive these errors:

`solana@rpc04:~/lite-rpc$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.79s
     Running unittests src/lib.rs (target/debug/deps/lite_rpc-ab3c453a9affed73)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/lite_rpc-11bcf71787ba803a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/blockhash.rs (target/debug/deps/blockhash-abeeb88be06cea4d)

running 1 test
test blockhash ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 30.03s

     Running tests/client.rs (target/debug/deps/client-93a6a4be5eef72b7)

running 2 tests
2023-03-14T20:30:17.263723Z  INFO client: Z5rKRR777M2qYYKN4kfnsCUeFr1PAKZ3QgsVEmkYLBLEiAdz29ppATS6pVjdoK87C1ZBe6GuWBrFH5BrwJX2aHW
test send_and_confirm_tx_rpc_client ... FAILED
test send_and_confirm_txs_get_signature_statuses ... FAILED

failures:

---- send_and_confirm_tx_rpc_client stdout ----
thread 'send_and_confirm_tx_rpc_client' panicked at 'called `Result::unwrap()` on an `Err` value: Error { request: None, kind: TransactionError(InstructionError(0, InvalidInstructionData)) }', tests/client.rs:37:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- send_and_confirm_txs_get_signature_statuses stdout ----
thread 'send_and_confirm_txs_get_signature_statuses' panicked at 'called `Result::unwrap()` on an `Err` value: Error processing Instruction 0: invalid instruction data', tests/client.rs:24:10

failures:
    send_and_confirm_tx_rpc_client
    send_and_confirm_txs_get_signature_statuses

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 4.82s

error: test failed, to rerun pass `--test client``

When I just run the bench, it never is able to confirm a transaction. I have funds in the payer wallet and can see the failed txs on solscan showing the same error above.

Thanks

**Comment by aniketfuryrocks** [comment]
the tests are fixed in the #28 branch
What are u running the lite-rpc against ?

**Comment by jnikoletich** [comment]
Looks like the error is gone. I noticed that it is only sending the same TX multiple times vs sending 20k individual txs. Is that by design?

**Comment by aniketfuryrocks** [comment]
@jnikoletich Noticed, the yarn test remains un fixed. The rust one seems to run as intended.
